### PR TITLE
Annual WeBWorK report

### PR DESCRIPTION
**Pull request by Alex-Jordan**
Here's a report about the hosting service for the blog. I put it in for December 28, but no rush. If it posts later and you'd like the date to be accurate, we can change the folder tree.

### CODE REVIEW

**Comment by bnmnetp** [comment]
Thanks Alex,

I had started an outline for my own post about Runestone yesterday, so it will be good to get this out there and then followup with my own next week.

Did you really want to include some of the text files with names of schools in the PR? I'm thinking `sorted.txt` and others should while we are missing `master.rst` that includes your post?


I'll make sure Jane agrees with those numbers before I post. 😄

**Comment by Alex-Jordan** [comment]
Oops, I did not git add carefully. I will review but no power right now.
Only phone.

**Comment by bnmnetp** [comment]
OK, stay warm!

I also verified with Jane that you two have a system... so never mind that comment.

**Comment by Alex-Jordan** [comment]
Now with only the one file this should have...

**Comment by Alex-Jordan** [comment]
pinging about this. If it gets posted I can send out a message to subscribers.

**Comment by bnmnetp** [comment]
It has been up since December 28.

**Comment by Alex-Jordan** [comment]
Oops, sorry! I should have checked. In my head it was tied to the PR closing.

**Pull request closed without merging**
